apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  strategy:
    blueGreen:
      activeService: {{ .Values.service.activeName }}
      previewService: {{ .Values.service.previewName }}
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
