replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/backend-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  activeName: backend-service
  previewName: backend-preview-service
  port: 80
  targetPort: 8080

rollout:
  blueGreen:
    autoPromotionEnabled: true

ingress:
  enabled: true
  host: api.marmil.co
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: app-shared
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789012:certificate/4b5e7d68-8d5e-49e2-a57f-0a1045800819
    external-dns.alpha.kubernetes.io/hostname: api.marmil.co

env:
  ASPNETCORE_URLS: http://+:8080
  OTEL_SERVICE_NAME: backend-api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc

resources: {}
